### ISSUE TITLE
manage.py: Don't format column names and aliases that are also SQL keywords

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/notebooks-ocds#27]
For example:

* 'extension' in https://colab.research.google.com/github/open-contracting/kingfisher_notebook_components/blob/main/check_scope.ipynb#scrollTo=qFbWPY5Eq7fv&line=8&uniqifier=1
* 'language' in https://kingfisher-summarize.readthedocs.io/en/latest/database.html#release-summary

We can use this issue to collect any other examples and then update the commands in `manage.py` to use the `--placeholder` command-line option to keep them untouched.

**Comment by jpmckinney** [comment]
Easier to just not use SQL keywords, which I've done (`ocds_extension`, `contract_implementation`).
