### ISSUE TITLE
Group all queries that depend on the DRT output in the same section

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/notebooks-ocds#39]
In https://github.com/open-contracting/notebooks-ocds/pull/38 I added a step to confirm that the DRT checks are complete before querying their output.

Some other queries depend on the DRT output too:

* Local extensions and additional fields and codes
* Deprecated fields

We should group all the queries that depend on the DRT output in the same section so that it's clear that analysts need to wait for the DRT checks to be complete before running them.

**Comment by jpmckinney** [comment]
I've instead just added a note to that section. Better to group thematically rather than by dependency.
