### ISSUE TITLE
component_check_structure: error message when running 'Error summary section'

### ISSUE THREAD

**Issue by fppenna** [open-contracting/notebooks-ocds#54]
Excecuted this section in the "Data quality feedback template" notebook and got the following error: 
```
(psycopg2.errors.AmbiguousColumn) column reference "field" is ambiguous
LINE 61:     field,
```
I resolved the error by adding "errors.field" in the last SELECT and GROUP BY clause as shown below. However, I am unsure if this correction displays the table we expected
```
SELECT
    collection_id,
    error_type,
    errors.field,
    error,
    count(*) AS count,
    example_ocids,
    example_values
FROM
    errors
    JOIN examples USING (collection_id, error_type, error)
GROUP BY
    collection_id,
    error_type,
    errors.field,
    error,
    example_ocids,
    example_values;
```

**Comment by jpmckinney** [comment]
So in 3d55092 and baa81cdc7ee6adf8b513739617fed1c7548e7347, that `errors ->> 'field'` column was added, based on a change that Jen from ODS had made. I didn't check whether this change made sense, however.

If the column doesn't seem to be informative, we can just undo that change (remove 6 lines like `errors ->> 'field' AS field,\n",` and `field,`).

**Comment by fppenna** [comment]
I can confirm that makes sense to keep that column, as it's relevant for providing details in the structure and format report.

**Comment by jpmckinney** [comment]
Thank you for reporting. Fixed!
