### ISSUE TITLE
Consider replacing %run with %load

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/notebooks-ocds#6]
`%load` is currently [broken in Colab](https://github.com/googlecolab/colabtools/issues/42), but could be preferable to `%run` because analysts would be able to see what is being run and the imported files could be stored as `.py` files which would make version control easier. The downside is that `%load` dumps the entire import into a single cell, although there is an open [feature request](https://github.com/jupyter/notebook/issues/3487) to change that.

**Comment by jpmckinney** [comment]
Looks like we don't use `%load` (maybe we added something to kingfisher-colab in the intervening time).
