### ISSUE TITLE
Resampling by month in quality check notebook doesn't work

### ISSUE THREAD

**Issue by allakulov** [open-contracting/notebooks-ocds#66]
```
# Resample by month
release_dates = release_dates.set_index("date")
release_dates = release_dates.groupby(["collection_id", "release_type"]).resample("M").sum().reset_index()

plot_releases_by_month(release_dates)
```

The above code block in [template_data_quality_feedback.ipynb](https://github.com/open-contracting/notebooks-ocds/blob/main/template_data_quality_feedback.ipynb) needed to produce `release_dates` for `plot_releases_by_month(release_dates)` causes 

> ValueError: cannot insert release_type, already exists. 

Grouping and resampling together seems to complicate things. I've found a workaround by replacing the said code block with the following, which seems to work:
```
release_dates['date'] = release_dates['date'].dt.strftime('%Y-%m')
release_dates = release_dates.groupby(['collection_id', 'release_type', 'date']).agg({'release_count': 'sum'}).reset_index()
plot_releases_by_month(release_dates)
```
@yolile

**Comment by yolile** [comment]
Thank you, fixed with your suggestion!
